---
constellation:
  name: "ETHERDemoSingleOrbit"
  num_orbits: 1
  num_sats_per_orbit: 72
  phase_diff: false
  inclination_degree: 51.9
  eccentricity: 0.0000001
  arg_of_perigee_degree: 0.0
  mean_motion_rev_per_day: 14.80
  tle_output_filename: "tles_single_orbit_sgp.txt.tmp"

simulation:
  dynamic_state_algorithm: "algorithm_free_one_only_over_isls"
  output_dir: null # Set to a path or keep null
  end_time_hours: 24
  time_step_minutes: 1
  offset_ns: 0

satellite:
  altitude_m: 550000
  cone_angle_degrees: 30.0

earth:
  radius_m: 6378135.0
  isl_min_altitude_m: 80000

ground_stations:
  - name: "London"
    latitude: 51.5074
    longitude: -0.1278
    elevation_m: 30.0
  - name: "Perth"
    latitude: -31.9505
    longitude: 115.8605
    elevation_m: 30.0

network:
  gsl_interfaces:  
    number_of_interfaces: 1
    aggregate_max_bandwidth: 1.0

logging:
  is_debug: true
  file_name: "simulation.log"
