constellation:
  name: "Starlink-550"
  num_orbits: 12
  num_sats_per_orbit: 13
  phase_diff: true
  inclination_degree: 53
  eccentricity: 0.0000001
  arg_of_perigee_degree: 0.0
  mean_motion_rev_per_day: 15.19
  tle_output_filename: "tles_starlink_550_sgp.txt.tmp"

simulation:
  dynamic_state_algorithm: shortest_path_link_state
  output_dir: null # Set to a path or keep null
  end_time_hours: 24
  time_step_minutes: 10
  offset_ns: 0

satellite:
  altitude_m: 550000
  cone_angle_degrees: 25.0

earth:
  radius_m: 6378135.0
  isl_min_altitude_m: 80000

ground_stations:
  - name: "London"
    latitude: 51.5074
    longitude: -0.1278
    elevation_m: 30.0
  - name: "Perth"
    latitude: -31.9505
    longitude: 115.8605
    elevation_m: 30.0

network:
  gsl_interfaces:
    number_of_interfaces: 1
    aggregate_max_bandwidth: 1.0

logging:
  is_debug: false
  file_name: "simulation.log"
